name: spajam2022final
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cached_network_image:
  cloud_firestore: ^4.0.2
  cloud_functions: ^4.0.3
  confetti: ^0.7.0
  connectivity_plus: ^3.0.2
  cookie_jar:
  country_icons: ^2.0.2
  cupertino_icons:
  dio:
  dio_cookie_manager:
  firebase_analytics: ^10.0.2
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  firebase_crashlytics: ^3.0.4
  firebase_dynamic_links: ^5.0.4
  firebase_messaging: ^14.0.2
  firebase_storage: ^11.0.2
  flutter:
    sdk: flutter
  flutter_datetime_picker_bdaya:
  flutter_hooks:
  flutter_image_compress: ^1.1.3
  flutter_keyboard_visibility:
  flutter_local_notifications:
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_spinkit:
  font_awesome_flutter:
  freezed_annotation:
  gap:
  geoflutterfire:
    git:
      url: https://github.com/KosukeSaigusa/GeoFlutterFire.git
  geolocator: ^9.0.2
  # geoflutterfire: ^3.0.3
  google_maps_flutter: ^2.2.1
  google_sign_in: ^5.4.2
  hooks_riverpod: ^2.1.1
  image_picker: ^0.8.6
  intl:
  json_annotation:
  lottie: ^1.4.1
  package_info_plus: ^3.0.1
  path_provider:
  path_to_regexp:
  shimmer:
  simple_logger:
  tuple:
  uuid:

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_lints: ^2.0.1
  # flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.12
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.3
  pedantic_mono:

flutter:
  uses-material-design: true
  assets:
    # - assets/lotties/
    - assets/images/
    - assets/launcher_icons/launcher_icon-dev.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icons/launcher_icon-prod.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash_icons/splash_icon_light.png"
  color_dark: "#000000"
  image_dark: "assets/splash_icons/splash_icon_dark.png"
  fullscreen: true
  android_12:
    icon_background_color: "#ffffff"
    image: "assets/splash_icons/splash_icon_light.png"
    icon_background_color_dark: "#000000"
    image_dark: "assets/splash_icons/splash_icon_dark.png"
