#!/bin/sh

code=$(cat <<EOS
import Foundation

struct Env {

EOS
)

if [ -e "./ios/.env" ]; then
  while IFS='' read -r line || [[ -n "$line" ]]; do
    line="${line//[$'\r\n']}"
    trimline="${line//[$'\t\r\n ']}"
    if [ -n "$trimline" ]; then
      KEY="${line%%=*}"
      VALUE="${line##*=}"
      code=$(cat <<EOS
$code
  static let $KEY = "$VALUE"
EOS
)
        fi
    done < "./ios/.env"
fi

code=$(cat <<EOS
$code
}
EOS
)

echo "${code}" > "./ios/Runner/Environment.swift"

exit 0
